layout_spectrum: 0.9928315
typography_spectrum: 0.8853046
color:
  saturation: 0.4749104
  lightness: 1
  brandStrength: 0.4634292
  brandColors:
    - '#FCC49D'
    - '#FCFAF2'
    - '#BDAD90'
    - '#F26653'
    - '#BD6653'
  rhythmicContrast: 0.8651235
name: Mizuho Sato Flamenco
